name: CI

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [xfce , cinnamon, lxde, kde, x11, sway, minimal, hyprland]

    steps:
      - uses: actions/checkout@v2

      - name: Run build script
        run: |
          sudo bash build.sh ${{ matrix.build_type }}

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ matrix.build_type }}  # Tag release with the build type (xxx or yyy)
          prerelease: false
          title: "Auto build for ${{ matrix.build_type }}"
          files: /output/*  # Path to the output files, modify if necessary


